spring.application.name=API_Bancaire
spring.datasource.url=jdbc:postgresql://localhost:5432/API_Bancaire

spring.datasource.username=postgres

spring.datasource.password=Sayliami12/

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true